import type { ChecklistTemplate } from "./types";

export const CHECKLIST_TEMPLATES: ChecklistTemplate[] = [
	{
		id: "simples",
		name: "Simples",
		layout: {
			columns: 1,
			showCheckbox: true,
			showDividers: false,
			spacing: "comfortable",
		},
		style: { fontSize: "md", titleAlign: "left", backgroundColor: "#ffffff" },
		content: { title: "Minha Lista", items: ["", "", "", "", ""] },
	},
	{
		id: "lista-compras",
		name: "Lista de Compras",
		layout: {
			columns: 2,
			showCheckbox: true,
			showDividers: false,
			spacing: "compact",
		},
		style: { fontSize: "sm", titleAlign: "left", backgroundColor: "#ffffff" },
		content: {
			title: "Lista de Compras",
			items: [
				"Leite",
				"Ovos",
				"Pão",
				"Manteiga",
				"Queijo",
				"Presunto",
				"Arroz",
				"Feijão",
				"Macarrão",
				"Molho de tomate",
				"Frango",
				"Frutas",
				"Verduras",
				"Café",
			],
		},
	},
	{
		id: "limpeza",
		name: "Limpeza da Casa",
		layout: {
			columns: 1,
			showCheckbox: true,
			showDividers: true,
			spacing: "comfortable",
		},
		style: { fontSize: "md", titleAlign: "left", backgroundColor: "#ffffff" },
		content: {
			title: "Limpeza da Casa",
			items: [
				"Varrer e passar pano na sala",
				"Limpar o banheiro",
				"Lavar a louça",
				"Limpar o fogão",
				"Tirar o lixo",
				"Lavar roupas",
				"Organizar os quartos",
				"Limpar janelas",
			],
		},
	},
	{
		id: "tarefas-dia",
		name: "Tarefas do Dia",
		layout: {
			columns: 1,
			showCheckbox: true,
			showDividers: false,
			spacing: "comfortable",
		},
		style: { fontSize: "md", titleAlign: "left", backgroundColor: "#ffffff" },
		content: {
			title: "Tarefas de Hoje",
			items: [
				"Checar e-mails",
				"Reunião da manhã",
				"Almoço",
				"Revisar relatório",
				"Ligar para cliente",
				"Academia",
				"Fazer compras",
				"Preparar agenda de amanhã",
			],
		},
	},
	{
		id: "viagem",
		name: "Checklist de Viagem",
		layout: {
			columns: 2,
			showCheckbox: true,
			showDividers: false,
			spacing: "compact",
		},
		style: { fontSize: "sm", titleAlign: "left", backgroundColor: "#ffffff" },
		content: {
			title: "Checklist de Viagem",
			items: [
				"Passaporte / RG",
				"Passagens",
				"Hotel confirmado",
				"Seguro viagem",
				"Carregador",
				"Fones de ouvido",
				"Roupas",
				"Calçados",
				"Necessaire",
				"Remédios",
				"Câmera",
				"Dinheiro / cartão",
			],
		},
	},
	{
		id: "reuniao",
		name: "Reunião",
		layout: {
			columns: 1,
			showCheckbox: false,
			showDividers: true,
			spacing: "comfortable",
		},
		style: { fontSize: "md", titleAlign: "left", backgroundColor: "#ffffff" },
		content: {
			title: "Pauta da Reunião",
			items: [
				"Abertura e apresentação",
				"Revisão da pauta anterior",
				"Ponto 1:",
				"Ponto 2:",
				"Ponto 3:",
				"Discussão aberta",
				"Próximos passos",
				"Encerramento",
			],
		},
	},
];
