import type { ChecklistItem, ChecklistTemplate } from "./types";

function item(text: string): ChecklistItem {
	return { text, kind: "item" };
}

function group(text: string): ChecklistItem {
	return { text, kind: "group" };
}

export const CHECKLIST_TEMPLATES: ChecklistTemplate[] = [
	{
		id: "simples",
		name: "Simples",
		layout: {
			columns: 1,
			showCheckbox: true,
			showDividers: false,
			spacing: "comfortable",
			writingLines: 0,
		},
		style: { fontSize: "md", titleAlign: "left", backgroundColor: "#ffffff" },
		content: {
			title: "Minha Lista",
			items: [item(""), item(""), item(""), item(""), item("")],
		},
	},
	{
		id: "lista-compras",
		name: "Lista de Compras",
		layout: {
			columns: 2,
			showCheckbox: true,
			showDividers: false,
			spacing: "compact",
			writingLines: 0,
		},
		style: { fontSize: "md", titleAlign: "left", backgroundColor: "#ffffff" },
		content: {
			title: "Lista de Compras",
			items: [
				group("Laticínios"),
				item("Leite integral"),
				item("Ovos (dúzia)"),
				item("Manteiga"),
				item("Queijo mussarela"),
				item("Iogurte natural"),
				group("Mercearia"),
				item("Arroz branco 5kg"),
				item("Feijão carioca 1kg"),
				item("Macarrão espaguete"),
				item("Molho de tomate"),
				item("Azeite de oliva"),
				item("Café em pó"),
				item("Açúcar"),
				item("Sal"),
				group("Hortifruti"),
				item("Banana"),
				item("Maçã"),
				item("Tomate"),
				item("Alface"),
				item("Cenoura"),
				item("Cebola"),
				group("Carnes"),
				item("Frango (peito)"),
				item("Carne moída"),
				item("Linguiça"),
				group("Limpeza"),
				item("Detergente"),
				item("Desinfetante"),
				item("Esponja de louça"),
				item("Papel higiênico"),
			],
		},
	},
	{
		id: "limpeza",
		name: "Limpeza da Casa",
		layout: {
			columns: 1,
			showCheckbox: true,
			showDividers: true,
			spacing: "comfortable",
			writingLines: 0,
		},
		style: { fontSize: "md", titleAlign: "left", backgroundColor: "#ffffff" },
		content: {
			title: "Limpeza da Casa",
			items: [
				group("Sala e Quartos"),
				item("Varrer e passar pano no chão"),
				item("Aspirar tapetes e sofá"),
				item("Limpar pó dos móveis"),
				item("Organizar e guardar objetos"),
				item("Limpar vidros e espelhos"),
				group("Cozinha"),
				item("Lavar louça e panelas"),
				item("Limpar fogão e forno"),
				item("Limpar geladeira por fora"),
				item("Passar pano na bancada"),
				item("Tirar lixo"),
				group("Banheiro"),
				item("Limpar vaso sanitário"),
				item("Limpar pia e torneira"),
				item("Lavar box e azulejos"),
				item("Trocar toalhas"),
				group("Geral"),
				item("Lavar roupas"),
				item("Estender e guardar roupas"),
				item("Limpar área de serviço"),
				item("Trocar lençóis da cama"),
			],
		},
	},
	{
		id: "tarefas-dia",
		name: "Tarefas do Dia",
		layout: {
			columns: 1,
			showCheckbox: true,
			showDividers: false,
			spacing: "comfortable",
			writingLines: 0,
		},
		style: { fontSize: "md", titleAlign: "left", backgroundColor: "#ffffff" },
		content: {
			title: "Tarefas de Hoje",
			items: [
				group("Manhã"),
				item("Checar e-mails e mensagens"),
				item("Revisar agenda do dia"),
				item("Reunião da equipe"),
				item("Priorizar tarefas urgentes"),
				group("Tarde"),
				item("Almoço"),
				item("Responder pendências"),
				item("Revisar relatório semanal"),
				item("Ligar para clientes"),
				item("Atualizar status no projeto"),
				group("Noite"),
				item("Academia ou caminhada"),
				item("Fazer compras se necessário"),
				item("Preparar agenda de amanhã"),
				item("Leitura ou estudo"),
			],
		},
	},
	{
		id: "viagem",
		name: "Checklist de Viagem",
		layout: {
			columns: 2,
			showCheckbox: true,
			showDividers: false,
			spacing: "compact",
			writingLines: 0,
		},
		style: { fontSize: "sm", titleAlign: "left", backgroundColor: "#ffffff" },
		content: {
			title: "Checklist de Viagem",
			items: [
				group("Documentos"),
				item("Passaporte / RG"),
				item("CPF"),
				item("Passagens (impressas ou app)"),
				item("Reserva do hotel confirmada"),
				item("Seguro viagem"),
				item("Carteira de motorista"),
				item("Visto (se necessário)"),
				group("Finanças"),
				item("Cartão de crédito/débito"),
				item("Dinheiro em espécie"),
				item("Moeda local (viagem internacional)"),
				item("App do banco instalado"),
				group("Eletrônicos"),
				item("Celular carregado"),
				item("Carregador do celular"),
				item("Adaptador de tomada"),
				item("Power bank"),
				item("Fones de ouvido"),
				item("Câmera + carregador"),
				item("Notebook (se necessário)"),
				group("Roupas"),
				item("Roupas para cada dia"),
				item("Roupas íntimas extras"),
				item("Pijama"),
				item("Roupas para clima frio"),
				item("Roupas de banho / praia"),
				item("Calçados (casual + conforto)"),
				item("Chinelo"),
				group("Higiene e Saúde"),
				item("Escova e pasta de dente"),
				item("Shampoo e condicionador"),
				item("Desodorante"),
				item("Protetor solar"),
				item("Repelente"),
				item("Remédios de uso contínuo"),
				item("Analgésico / antitérmico"),
				item("Band-aid e antisséptico"),
				item("Antiemético (enjoo)"),
				group("Bagagem de Mão"),
				item("Documento de identidade"),
				item("Cartão de embarque"),
				item("Fone de ouvido"),
				item("Snacks para o trajeto"),
				item("Garrafa de água vazia"),
				item("Agasalho ou manta"),
				group("Casa — antes de sair"),
				item("Desligar tomadas e aparelhos"),
				item("Fechar janelas e portas"),
				item("Deixar chave com alguém"),
				item("Cancelar entregas/correspondência"),
				item("Regar plantas ou pedir ajuda"),
			],
		},
	},
	{
		id: "reuniao",
		name: "Reunião",
		layout: {
			columns: 1,
			showCheckbox: false,
			showDividers: true,
			spacing: "comfortable",
			writingLines: 0,
		},
		style: { fontSize: "md", titleAlign: "left", backgroundColor: "#ffffff" },
		content: {
			title: "Pauta da Reunião",
			items: [
				group("Abertura"),
				item("Boas-vindas e presença"),
				item("Revisão da ata anterior"),
				item("Objetivos da reunião"),
				group("Discussão"),
				item("Ponto 1:"),
				item("Ponto 2:"),
				item("Ponto 3:"),
				item("Dúvidas e contribuições"),
				group("Encerramento"),
				item("Próximos passos e responsáveis"),
				item("Prazos definidos"),
				item("Data da próxima reunião"),
				item("Encerramento"),
			],
		},
	},
];
